import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const scratch=path.resolve(root,'../..','work','test-data-'+Date.now());
fs.mkdirSync(scratch,{recursive:true});
async function start(){const p=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'0',DATA_DIR:scratch,ADMIN_LOGIN:'Admin',ADMIN_PASSWORD:'Admin123'}});const ready=await new Promise((resolve,reject)=>{p.stdout.on('data',d=>{const match=d.toString().match(/localhost:(\d+)/);if(match)resolve(match[1]);});p.once('error',reject);p.once('exit',code=>reject(Error(`Server exited ${code}`)));});return {p,base:`http://127.0.0.1:${ready}`};}
async function stop(p){const ended=once(p,'exit');p.kill();await ended;}
test('admin authentication, upload authorization, media ranges and persistence',async()=>{
 let server=await start();
 try{
  const initial=await(await fetch(server.base+'/api/stories')).json();assert.equal(initial.length,6);assert.ok(initial.every(s=>Number.isInteger(s.views)&&s.views>=1000&&s.views<=10000));
  assert.equal((await (await fetch(server.base+'/api/session')).json()).admin,false);
  const unauthorized=await fetch(server.base+'/api/stories',{method:'POST',body:'{}'});assert.equal(unauthorized.status,401);
  const forged=await fetch(server.base+'/api/stories',{method:'POST',headers:{Cookie:'flower_session=fake'},body:'{}'});assert.equal(forged.status,401);
  const wrong=await fetch(server.base+'/api/login',{method:'POST',body:JSON.stringify({login:'Admin',password:'wrong'})});assert.equal(wrong.status,401);
  const login=await fetch(server.base+'/api/login',{method:'POST',body:JSON.stringify({login:'Admin',password:'Admin123'})});assert.equal(login.status,200);
  const setCookie=login.headers.get('set-cookie');assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/SameSite=Strict/);
  const headers={Cookie:setCookie.split(';')[0]};
  assert.equal((await (await fetch(server.base+'/api/session',{headers})).json()).admin,true);
  const data=fs.readFileSync(path.join(root,'public/assets/flowers-1.jpg'));
  const upload=(bytes,auth=headers)=>fetch(server.base+'/api/admin/media',{method:'POST',headers:auth,body:bytes});
  const mediaResponse=await upload(data);assert.equal(mediaResponse.status,201);const media=await mediaResponse.json();assert.equal(media.type,'image');
  const mov=Buffer.concat([Buffer.alloc(4),Buffer.from('ftyp'),Buffer.from('qt  '),Buffer.alloc(4),data]);
  const movMedia=await (await upload(mov)).json();assert.equal(movMedia.type,'video');assert.match(movMedia.src,/\.mov$/);
  const movFile=await fetch(server.base+movMedia.src,{headers});assert.equal(movFile.headers.get('content-type'),'video/quicktime');
  const fakeHeic=await upload(Buffer.concat([Buffer.alloc(4),Buffer.from('ftypheic'),data]));assert.equal(fakeHeic.status,415);assert.match((await fakeHeic.json()).error,/ImageMagick|JPG/);
  const response=await fetch(server.base+'/api/stories',{method:'POST',headers,body:JSON.stringify({title:'Проверка публикации',category:'bouquets',media})});assert.equal(response.status,201);const item=await response.json();
  assert.equal(item.src,media.src);
  const list=await(await fetch(server.base+'/api/stories')).json();assert.equal(list[0].id,item.id);
  const full=await fetch(server.base+item.src);assert.deepEqual(Buffer.from(await full.arrayBuffer()),data);
  const range=await fetch(server.base+item.src,{headers:{Range:'bytes=0-15'}});assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,16);
  const invalid=await upload(Buffer.from('<svg onload="alert(1)"></svg>'));assert.equal(invalid.status,400);
  const missingTitle=await fetch(server.base+'/api/stories',{method:'POST',headers,body:JSON.stringify({title:'',media:await (await upload(data)).json()})});assert.equal(missingTitle.status,400);
  const origin=await fetch(server.base+'/api/stories',{method:'POST',headers:{Origin:'https://other.example'},body:'{}'});assert.equal(origin.status,403);
  assert.ok(Number.isInteger(item.views)&&item.views>=1000&&item.views<=10000);
  const expectedViews=Math.min(10000,item.views+1);
  const view=await fetch(server.base+`/api/stories/${item.id}/view`,{method:'POST'});assert.equal((await view.json()).views,expectedViews);
  const request=async(url,method='GET',payload,auth=headers)=>fetch(server.base+url,{method,headers:auth,...(payload===undefined?{}:{body:JSON.stringify(payload)})});
  assert.equal((await request('/api/admin/stories','GET',undefined,{})).status,401);
  for(const [url,method] of [['/api/admin/media','POST'],[`/api/admin/stories/${item.id}`,'PATCH'],[`/api/admin/stories/${item.id}`,'DELETE'],[`/api/admin/stories/${item.id}/restore`,'POST'],['/api/admin/stories/reorder','POST'],['/api/admin/contacts','PUT']])assert.equal((await request(url,method,{},{})).status,401);
  assert.equal((await request(`/api/admin/stories/${item.id}`,'PATCH',{caption:'blocked'},{...headers,Origin:'https://other.example'})).status,403);
  const draftResponse=await request('/api/stories','POST',{title:'Новый черновик',caption:'Виден только администратору',status:'draft',media:await (await upload(data)).json()});assert.equal(draftResponse.status,201);const draft=await draftResponse.json();
  assert.equal((await (await request('/api/stories')).json()).some(s=>s.id===draft.id),false);
  assert.equal((await fetch(server.base+draft.src)).status,404);assert.equal((await request(draft.src)).status,200);
  assert.equal((await request(`/api/stories/${draft.id}/view`,'POST')).status,404);
  const editResponse=await request(`/api/admin/stories/${draft.id}`,'PATCH',{title:'Обновлённая история',caption:'Новое описание <b>как текст</b>',status:'published',expectedUpdatedAt:draft.updatedAt});assert.equal(editResponse.status,200);const edited=await editResponse.json();
  assert.equal((await (await request('/api/stories')).json()).find(s=>s.id===draft.id).caption,'Новое описание <b>как текст</b>');assert.equal((await fetch(server.base+draft.src)).status,200);
  assert.equal((await request(`/api/admin/stories/${draft.id}`,'PATCH',{title:'Устаревшее',expectedUpdatedAt:'stale'})).status,409);
  assert.equal((await request(`/api/admin/stories/${draft.id}`,'PATCH',{caption:'x'.repeat(401)})).status,400);
  const replacement=fs.readFileSync(path.join(root,'public/assets/flowers-2.jpg'));
  assert.equal((await request('/api/stories','POST',{title:'Чужой файл',media:{src:item.src}})).status,400);
  assert.equal((await request('/api/stories','POST',{title:'Нет такого файла',media:{src:'/uploads/00000000-0000-4000-8000-000000000000.jpg'}})).status,400);
  assert.equal((await request('/api/stories','POST',{title:'Мимо папки',media:{src:'/uploads/../../etc/passwd'}})).status,400);
  const replaced=await (await request(`/api/admin/stories/${draft.id}`,'PATCH',{media:await (await upload(replacement)).json(),expectedUpdatedAt:edited.updatedAt})).json();assert.notEqual(replaced.src,draft.src);assert.equal(replaced.title,'Обновлённая история');assert.equal((await fetch(server.base+draft.src)).status,404);
  assert.equal(fs.existsSync(path.join(scratch,'uploads',path.basename(draft.src))),false);
  let ordered=await (await request('/api/admin/stories')).json();const ids=ordered.filter(s=>!s.deletedAt).map(s=>s.id).reverse();
  assert.equal((await request('/api/admin/stories/reorder','POST',{ids:ids.slice(1)})).status,409);
  assert.equal((await request('/api/admin/stories/reorder','POST',{ids:ids.map(()=>ids[0])})).status,409);
  assert.equal((await request('/api/admin/stories/reorder','POST',{ids})).status,200);assert.deepEqual((await (await request('/api/stories')).json()).map(s=>s.id),ids);
  assert.equal((await request(`/api/admin/stories/${draft.id}`,'DELETE')).status,200);
  assert.equal((await (await request('/api/stories')).json()).some(s=>s.id===draft.id),false);assert.equal((await fetch(server.base+replaced.src)).status,404);
  assert.ok((await (await request('/api/admin/stories')).json()).find(s=>s.id===draft.id).deletedAt);
  assert.equal((await request(`/api/admin/stories/${draft.id}`,'PATCH',{title:'Нельзя'})).status,409);
  const restored=await (await request(`/api/admin/stories/${draft.id}/restore`,'POST')).json();assert.equal(restored.status,'draft');assert.equal(restored.deletedAt,null);
  assert.equal((await (await request('/api/stories')).json()).some(s=>s.id===draft.id),false);
  const contactUpdate={telegram:'https://t.me/flower_test',max:'https://max.ru/flower_test',whatsapp:'https://wa.me/79991234567',address:'Тестовая улица, 5',coordinates:'55.7522,37.6155'};
  assert.equal((await request('/api/admin/contacts','PUT',{...contactUpdate,max:'javascript:alert(1)'})).status,400);
  assert.equal((await request('/api/admin/contacts','PUT',contactUpdate)).status,200);assert.deepEqual(await (await request('/api/contacts')).json(),contactUpdate);
  assert.equal((await request('/api/admin/contacts','PUT',{telegram:'https://t.me/tochnoda_ru',max:'',whatsapp:''})).status,200);
  const logout=await fetch(server.base+'/api/logout',{method:'POST',headers});assert.equal(logout.status,200);
  assert.equal((await (await fetch(server.base+'/api/session',{headers})).json()).admin,false);
  assert.equal((await fetch(server.base+'/api/stories',{method:'POST',headers,body:'{}'})).status,401);
  const contacts=await (await fetch(server.base+'/api/contacts')).json();assert.equal(contacts.telegram,'https://t.me/tochnoda_ru');
  for(let i=0;i<5;i++)assert.equal((await fetch(server.base+'/api/login',{method:'POST',body:JSON.stringify({login:'Admin',password:'wrong'})})).status,401);
  assert.equal((await fetch(server.base+'/api/login',{method:'POST',body:JSON.stringify({login:'Admin',password:'Admin123'})})).status,429);
  await stop(server.p);server=await start();const persisted=await(await fetch(server.base+'/api/stories')).json();assert.equal(persisted.find(s=>s.id===item.id).views,expectedViews);assert.deepEqual(persisted.map(s=>s.id),ids.filter(id=>id!==draft.id));assert.equal((await fetch(server.base+replaced.src)).status,404);
 }finally{await stop(server.p);}
});
